# This workflow will build a Java project with Maven

name: Java CI with Maven in Linux 1

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy: 

    name: Build With default Java
    steps:
    - uses: actions/checkout@v2
    - name: Show Java version
      run: java -version
    - name: Build with Maven
      run: mvn -f myproject/pom.xml clean verify